### ISSUE TITLE
HTML button do nothing 

### ISSUE THREAD

**Issue by emezeta** [jobisoft/HtmlSourceEditor#1]
Hi, I don't see any issues reports, thus I don't know if this is a reported problem or not?

I just installed the extension on Thund 102.13.1 (64-bit). The HTML button appears correctly in the bar, the problem is that it does nothing when I click it when editing a message.

Unfortunately nothing more I can add about this. Is there any tip to put HtmlSourceEditor  in debug mode?
Tks.

**Comment by jobisoft** [comment]
Oh wow, I did a beginners mistake. I used a feature only available in Thunderbird 115, but allowed the add-on to be installed in Thunderbird 102 without checking if the feature is available. Thunderbird 102 does not like it.

I will try to change the add-on to use the feature only in TB115.

**Comment by jobisoft** [comment]
Should be fixed in v1.5:
https://addons.thunderbird.net/addon/html-source-editor/

**Comment by emezeta** [comment]
> Should be fixed in v1.5: https://addons.thunderbird.net/addon/html-source-editor/

It's okay. This version is working fine. The issue can be closed as far as I am concerned. Thank you
