### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by adefaria** [jobisoft/HtmlSourceEditor#3]
This is not working in Thunderbird 102.14.0. I see no way to edit any HTML.

**Comment by openmindculture** [comment]
I cannot confirm the error. I have just discovered this extension and it works for me.
I just added the extension to Thunderbird 115.9.0 on Ubuntu Linux, default English system language. I started a new (HTML format) message and got a new button on the top right corner above the message pane: "Source (HTML)".

**Comment by adefaria** [comment]
I think I just did not know how to find it. I got it now.

**Comment by jobisoft** [comment]
Heads-up: I am planing to move the button from its current location to the format-toolbar (where bold and color can be changed). I will announce it via a message/tab being opened in TB, but since we are here, wanted to share that with you now already.
