### ISSUE TITLE
Translation of "Source (HTML)" in Chinese is incorrect

### ISSUE THREAD

**Issue by starsang1995** [jobisoft/HtmlSourceEditor#7]
![图片](https://github.com/jobisoft/HtmlSourceEditor/assets/42469315/23ab5719-cfad-4b16-ab07-9464665d98bf)

The "Source (HTML)" here should be translated into "源代码 (HTML)" instead of "来源 (HTML)" which makes more sense.

**Comment by MountComb** [comment]
+1 for that. The current translation is a bit misleading.
