### ISSUE TITLE
Blank window in Thunderbird 128

### ISSUE THREAD

**Issue by DeronLJ** [jobisoft/HtmlSourceEditor#8]
I just upgraded to Thunderbird 128.0esr, and now when click on the Source (HTML) button, the window it opens is blank. From the Thunderbird error console:
`

    window.controllers/Controllers is deprecated. Do not use it for UA detection. ace.js:1:18480
    composeWindow.document.getElementById(...) is null ext-compose.js:487:6
        getComposeDetails chrome://messenger/content/parent/ext-compose.js:487
        getComposeDetails chrome://messenger/content/parent/ext-compose.js:1826
        InterpretGeneratorResume self-hosted:1417
        AsyncFunctionNext self-hosted:804
    Error: An unexpected error occurred source-editor.js:100:27
        initialize moz-extension://7aeaba30-27fb-4769-9684-054554831bd7/editor/source-editor.js:100
        <anonymous> moz-extension://7aeaba30-27fb-4769-9684-054554831bd7/editor/source-editor.js:267`

OS: Linux (Kubuntu noble 24.04 x86_64)

**Comment by jobisoft** [comment]
That is a know regression in Thunderbird 128. Fix is filed. Triggered by manually removing the encrypt button from the compose UI.
https://bugzilla.mozilla.org/show_bug.cgi?id=1906833

**Comment by DeronLJ** [comment]
Thank you for the quick response. I put the Encrypt button back on my toolbar, and the HTML Source Editor works again! I never would have guessed. I'm going to mark this as closed myself, since a bug has been filed against Thunderbird.
